#Pivotal Tracker API token
TRACKER_TOKEN = ""

TWITTER_CONSUMER_KEY =""
TWITTER_CONSUMER_SECRET =""
TWITTER_OAUTH_TOKEN = ""
TWITTER_OAUTH_SECRET = ""

GETSAT_USERNAME = ""
GETSAT_PASSWORD = ""

JIRA_USERNAME = ""
JIRA_PASSWORD = ""

BASECAMP_USERNAME = ""
BASECAMP_PASSWORD = ""
BASECAMP_PROJECT_ID = ""

BITLY_API_KEY = "" 

